Refactor
Shegsdev/Questioner pull request #16
Opened 2019-01-08 04:27 UTC by Shegsdev

I uninstalled the templating engine and rearrange my folder structure. I also implemented the MVC pattern for modularization and maintenance. The currently written API endpoints are working as expected.

2019-01-09 08:24 UTC, saheedt requested changes

2019-01-09 08:24 UTC, saheedt commented on app.js
> +app.patch('/questions/:id/upvote', (req, res) => {
remove all route instance from your app.js / server.js. All api routes should be in the api route file.

2019-01-09 08:24 UTC, saheedt commented on .eslintrc
> +    "rules": {
install the airbnb rules `eslint-config-airbnb-base` module via `npm` and add this to your eslint rules.

```
 "extends": "airbnb-base"
```

2019-01-09 12:13 UTC, Shegsdev commented on app.js
> +app.patch('/questions/:id/upvote', (req, res) => {
Fixed.
https://github.com/Shegsdev/Questioner/pull/18

2019-01-09 12:15 UTC, Shegsdev commented on .eslintrc
> +    "rules": {
```
    "rules": {...
    },
    "extends": "airbnb-base"
```
updated .eslintrc file

2019-01-10 20:02 UTC, Shegsdev commented
Ready to merge.

2019-01-13 12:16 UTC, merged